[0m16:13:52.585665 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C8FCC1A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C8F488970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C8F4886D0>]}


============================== 16:13:52.592679 | d997ce5f-ac01-4d54-9fe6-8da6fc2cd6a0 ==============================
[0m16:13:52.592679 [info ] [MainThread]: Running with dbt=1.5.2
[0m16:13:52.593665 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Ð•Ð³Ð¾Ñ€\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:14:06.419548 [debug] [MainThread]: Starter project path: C:\anaconda\lib\site-packages\dbt\include\starter_project
[0m16:14:15.518698 [info ] [MainThread]: 
Your new dbt project "dbt_data_vault" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:14:15.520696 [debug] [MainThread]: Command `dbt init` succeeded at 16:14:15.520696 after 22.99 seconds
[0m16:14:15.521698 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C8FCC1A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C925D0DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C900C6670>]}
[0m16:14:15.522706 [debug] [MainThread]: Flushing usage events
[0m16:18:05.299558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018796B61250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187963288E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018796328700>]}


============================== 16:18:05.303555 | af75bd2a-a273-47ec-a152-1d4d6f29ed5b ==============================
[0m16:18:05.303555 [info ] [MainThread]: Running with dbt=1.5.2
[0m16:18:05.305557 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Ð•Ð³Ð¾Ñ€\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:18:05.306556 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ð•Ð³Ð¾Ñ€\PycharmProjects\pythonProject3\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:18:05.307557 [debug] [MainThread]: Command `dbt deps` failed at 16:18:05.307557 after 0.05 seconds
[0m16:18:05.308556 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018796B61250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018796328190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018796328AF0>]}
[0m16:18:05.308556 [debug] [MainThread]: Flushing usage events
[0m14:51:56.336161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BE2D1370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BDA99A00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BDA99760>]}


============================== 14:51:56.336161 | 7b1edbdc-d413-425a-9ea9-e17fea50f2c7 ==============================
[0m14:51:56.336161 [info ] [MainThread]: Running with dbt=1.5.2
[0m14:51:56.336161 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Ð•Ð³Ð¾Ñ€\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:51:56.351804 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ð•Ð³Ð¾Ñ€\PycharmProjects\pythonProject3\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:51:56.353426 [debug] [MainThread]: Command `dbt run` failed at 14:51:56.353253 after 0.06 seconds
[0m14:51:56.353426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BE2D1370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BDA99970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BDA999D0>]}
[0m14:51:56.353426 [debug] [MainThread]: Flushing usage events
